export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const GET_VIDEOGAME_DETAIL = "GET_VIDEOGAME_DETAIL";
export const CATEGORIES_FILTER = "GET_GENRES";
export const FILTER_BY_PLATFORM = "FILTER_BY_PLATFORM";
export const POST_VIDEOGAME = "POST_VIDEOGAME";
export const GET_PLATFORMS = "GET_PLATFORMS";
export const GET_GENRES = "GET_GENRES";
export const FILTER_BY_GENRE = "FILTER_BY_GENRE";
export const ALPHABETICAL_SORT = "ALPHABETICAL_SORT";
export const RATING_SORT = "RATING_SORT";

